services:
  #sets up how to make the source data available
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  wms:
    #srs sets the coordinate reference systems as which you want to make your data available. MapProxy reprojects the source data very well to these projections.
    srs: ['EPSG:3857']
    image_formats: ['image/jpeg', 'image/png']
    md:
      # metadata used in capabilities documents
      title: dgu.hr (mapproxy)
      abstract: This is the MapProxy for Croatian Layers.
      fees: 'None'


layers:
  #sets up which layers you want to make available using the services above. You can add many, but let's stick to osm data here.
  - name: osm_demo
    title: Open Streetmap Tiles (test)
    sources: [osm_cache] #this layer should use the osm_cache (defined below) as it's source.

  - name: dgu_2022_2023_lidar
    title: dgu.hr - Croatia 2022-2023 Aerial imagery LiDAR
    sources: [dgu_cache_2022_2023_lidar]

  - name: dgu_2023
    title: dgu.hr - Croatia 2023 South+East Aerial imagery
    sources: [dgu_cache_2023]

  - name: dgu_2021_2022
    title: dgu.hr - Croatia 2021-2022 Aerial imagery
    sources: [dgu_cache_2021_2022]

  - name: dgu_2019_2020
    title: dgu.hr - Croatia 2019-2020 Aerial imagery
    sources: [dgu_cache_2019_2020]

  - name: dgu_2019
    title: dgu.hr - Croatia 2019 South+East Aerial imagery
    sources: [dgu_cache_2019]

  - name: dgu_2017_2018
    title: dgu.hr - Croatia 2017-2018 Aerial imagery
    sources: [dgu_cache_2017_2018]

  - name: dgu_2018
    title: dgu.hr - Croatia 2018 West Aerial imagery
    sources: [dgu_cache_2018]

  - name: dgu_2017
    title: dgu.hr - Croatia 2017 South+East Aerial imagery
    sources: [dgu_cache_2017]

  - name: dgu_2014_2016
    title: dgu.hr - Croatia 2014-2016 Aerial imagery
    sources: [dgu_cache_2014_2016]

  - name: dgu_2011
    title: dgu.hr - Croatia 2011 Aerial imagery
    sources: [dgu_cache_2011]

  - name: dgu_TK25_NOVI
    title: dgu.hr - Topo 25 new
    sources: [dgu_cache_TK25_NOVI]

  - name: dgu_TK_25
    title: dgu.hr - Topo 25
    sources: [dgu_cache_TK_25]

  - name: dgu_HOK
    title: dgu.hr - HOK
    sources: [dgu_cache_HOK]

caches:
  #setup the cache for the open streetmap tiles. This cache is used by the layer above.
  osm_cache:
    sources: [osm_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
    grids: [webmercator_hr]

  dgu_cache_2022_2023_lidar:
    sources: [dgu_wms_2022_2023_lidar]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2023:
    sources: [dgu_wms_2023]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2021_2022:
    sources: [dgu_wms_2021_2022]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2019_2020:
    sources: [dgu_wms_2019_2020]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2019:
    sources: [dgu_wms_2019]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2017_2018:
    sources: [dgu_wms_2017_2018]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2018:
    sources: [dgu_wms_2018]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2017:
    sources: [dgu_wms_2017]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2014_2016:
    sources: [dgu_wms_2014_2016]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_2011:
    sources: [dgu_wms_2011]
    format: image/jpeg
    grids: [webmercator_hr]

  dgu_cache_TK25_NOVI:
    sources: [dgu_wms_TK25_NOVI]
    format: image/png
    grids: [webmercator_hr]

  dgu_cache_TK_25:
    sources: [dgu_wms_TK_25]
    format: image/png
    grids: [webmercator_hr]

  dgu_cache_HOK:
    sources: [dgu_wms_HOK]
    format: image/png
    grids: [webmercator_hr]



sources:
  osm_tiles:
    #the osm_tiles source refers to the openstreetmap.org tiles. These will be downloaded upon request (if not already cached) and served by MapProxy
    type: tile
    url: http://c.tile.openstreetmap.org/%(tms_path)s.%(format)s
    #url: http://c.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
    grid: webmercator_hr

  dgu_wms_2022_2023_lidar:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_lidar_2022_2023/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_lidar_2022_2023/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [13.01,41.62,19.45,46.55]   # from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2023:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2023/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2023/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [15.366475949222318,42.34007771200276,19.195753828425417,46.50756780735698]
      bbox_srs: 'EPSG:4326'

  dgu_wms_2021_2022:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2021_2022/ows?
      #url: https://geoportal.dgu.hr/services/inspire/orthophoto_2021_2022/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [12.7076,41.6049,19.7065,46.5583]   # from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2019_2020:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2019_2020/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2019_2020/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [12.7076,41.6049,19.7065,46.5583]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2019:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2019/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2019/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [16.329741833450203,41.85529836594651,19.967427497207495,46.939363002882104]	# from geoportal.dgu.hr / Metapodaci: https://geoportal.nipp.hr/geonetwork/srv/hrv/catalog.search#/metadata/7b4412ae-f9b9-40b4-bc83-42e14de34178
      bbox_srs: 'EPSG:4326'

  dgu_wms_2017_2018:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2017_2018/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2017_2018/ows?authKey=12345
      layers: OI.OrthoimageCoverage
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2018:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2018/ows?
      #url:  https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2018/ows?authKey=12345
      layers: OI.OrthoImagery
    coverage:
      bbox: [12.536174218942529,42.06797417811887,16.462278564586732,46.83872441283675]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2017:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2017/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2017/ows?authKey=12345
      layers: OI.OrthoImagery
    coverage:
      bbox: [16.165605,42.12978,20.05138,46.81305]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2014_2016:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/inspire/orthophoto_2014-2016/ows?
      #url: https://geoportal.dgu.hr/services/auth/inspire/orthophoto_2014-2016/ows?authKey=12345
      layers: OI.OrthoImagery
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_2011:
    type: wms
    req:
      #url: https://geoportal.dgu.hr/services/dof/ows?
      url: https://geoportal.dgu.hr/ows?
      #url: https://geoportal.dgu.hr/services/auth/dof/ows?authKey=12345
      #layers: DOF5_NOVI
      #layers: DOF5_2011
      layers: DOF
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'
      #bbox_srs: 'EPSG:3857'
      #bbox_srs: 'EPSG:3765'


  dgu_wms_TK25_NOVI:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/tk/ows?
      layers: tk:TK25_NOVI
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_TK_25:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/tk/ows?
      layers: tk:TK25
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'

  dgu_wms_HOK:
    type: wms
    req:
      url: https://geoportal.dgu.hr/services/hok/ows?
      layers: HOK5
    coverage:
      bbox: [13.01,41.62,19.45,46.55]		# from geoportal.dgu.hr / Metapodaci
      bbox_srs: 'EPSG:4326'


grids:
  #osm_grid:
    #this srs and origin specify a grid that can be used elsewhere in the configuration. In this example it is used for the osm_tiles source. These settings are correct for openstreetmap.org tiles.
    #The google mercator srs is used (also called EPSG:900913), and the origin of the tiles is north-west). If you get this wrong, you might very well get an all-blue world.
    #srs: EPSG:3857
    #origin: nw

  webmercator_hr:
    base: GLOBAL_WEBMERCATOR
    #bbox: [12.5, 41.5, 20, 47]	# approx. limit to Croatia
      #bbox_srs: 'EPSG:4326'
    #bbox_srs: 'EPSG:3857'



globals:
  #next are some global configuration options for MapProxy. They mostly explain themselves, or can be looked-up in the MapProxy docs.
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'
    tile_lock_dir: './cache_data/tile_locks'

  tiles:
    expires_hours: 8760		# cache for a year

  # image/transformation options
  image:
      resampling_method: bilinear
      #paletted: false
      #jpeg_quality: 90
      formats:
        image/png:
          transparent: true
